### ISSUE TITLE
程序日志显示评论发送成功，但实际上bilibili里没有评论

### ISSUE THREAD

**Issue by PawNzZi** [yanyao2333/BiliGPTHelper#1]
发现两个问题：
1-同一个视频要第二次at才会发送评论、首次at只会写进缓存不会发送评论，第二次之后的at就去缓存读取数据发送了。
2-评论发送成功，调用发送评论接口成功了，拿到正确的响应，但是视频的评论中没有这条评论，不知道是不是阿b秒删，还是程序问题。

**Comment by roitium** [comment]
第一个确实是bug，我尝试修复一下
第二个问题我这边也有这样的情况，api提示发送成功，但是收不到消息，这种问题并不好排查，我测试了几次觉得可能就是你b对评论shadow ban的问题，这个没办法。

**Comment by roitium** [comment]
我trace了一遍流程，感觉好像没啥问题啊，有bug发生时的日志没有？

**Comment by PawNzZi** [comment]
> 第一个确实是bug，我尝试修复一下 第二个问题我这边也有这样的情况，api提示发送成功，但是收不到消息，这种问题并不好排查，我测试了几次觉得可能就是你b对评论shadow ban的问题，这个没办法。

`    async def start_chain(self):

        try:
            _LOGGER.info("正在启动摘要处理链，开始将上次未处理完的视频加入队列")
            await self._on_start()
            while True:
                if self.max_tokens is not None and self.now_tokens >= self.max_tokens:
                    _LOGGER.warning(
                        f"当前已使用token数{self.now_tokens}，超过最大token数{self.max_tokens}，摘要处理链停止运行"
                    )
                    raise asyncio.CancelledError

                # 从队列中获取摘要
                at_items: AtItems = await self.summarize_queue.get()
                if at_items.get("item").get("uuid", None) is not None:`
上面描述的第一个问题，我debug了多次之后发现是   `at_items: AtItems = await self.summarize_queue.get()`  这行代码出的问题，设置完缓存后进入到while循环中，执行到这行代码的时候就报错结束循环了，后面的代码没执行，也就没发送评论。不知道你找到的原因是不是这个。
至于发送成功后视频中没有评论，我也测试了几百次，就是被B站给秒删，一部分能成功，一部分被秒删。因该被误认为是机器人了。

**Comment by roitium** [comment]
奇怪，我这边真的没查出来问题所在，我运行起来一切正常，这行代码是阻塞的，就是等待队列中被放入数据，按理来说没有出错的可能性

**Comment by roitium** [comment]
最好还是能有报错日志吧，这样堆栈信息啥的也好追溯

**Comment by PawNzZi** [comment]
> 最好还是能有报错日志吧，这样堆栈信息啥的也好追溯

`2023-09-25 08:33:59.730 | DEBUG    | src.chain.summarize:start_chain:563 - 正在将结果加入发送队列，等待回复
2023-09-25 08:33:59.730 | DEBUG    | src.chain.summarize:_send_reply:307 - 正在将结果加入发送队列，等待回复
E:\biliGPT\BiliGPTHelper-master\src\chain\summarize.py:310: RuntimeWarning: coroutine 'Queue.put' was never awaited
  self.reply_queue.put(reply_data)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-09-25 08:33:59.736 | DEBUG    | src.chain.summarize:_send_reply:311 - 结果加入发送队列成功
2023-09-25 08:33:59.786 | DEBUG    | src.chain.summarize:_send_reply:324 - 设置缓存成功
2023-09-25 08:33:59.786 | INFO     | src.chain.summarize:start_chain:567 - 111111111
Run time of job "Session.run.<locals>.qurey (trigger: interval[0:00:06], next run at: 2023-09-25 08:34:14 CST)" was missed by 0:00:04.137293
Run time of job "Listen.listen_at (trigger: interval[0:00:20], next run at: 2023-09-25 08:34:30 CST)" was missed by 0:00:01.343354`

执行到这行代码时 
``at_items: AtItems = await self.summarize_queue.get()` `
跳出了while循环，控制台就出现
```
Run time of job "Session.run.<locals>.qurey (trigger: interval[0:00:06], next run at: 2023-09-25 08:34:14 CST)" was missed by 0:00:04.137293
Run time of job "Listen.listen_at (trigger: interval[0:00:20], next run at: 2023-09-25 08:34:30 CST)" was missed by 0:00:01.343354
````
的提示。

**Comment by PawNzZi** [comment]
![企业微信截图_16956264341288](https://github.com/yanyao2333/BiliGPTHelper/assets/26763995/7666fcb1-72fa-4b88-b234-b776b53a5d42)
`  async def get(self):
        """Remove and return an item from the queue.

        If queue is empty, wait until an item is available.
        """
        while self.empty():
            getter = self._get_loop().create_future()
            self._getters.append(getter)
            try:
                await getter
            except:
                getter.cancel()  # Just in case getter is not done yet.
                try:
                    # Clean self._getters from canceled getters.
                    self._getters.remove(getter)
                except ValueError:
                    # The getter could be removed from self._getters by a
                    # previous put_nowait call.
                    pass
                if not self.empty() and not getter.cancelled():
                    # We were woken up by put_nowait(), but can't take
                    # the call.  Wake up the next in line.
                    self._wakeup_next(self._getters)
                raise
        return self.get_nowait()`
这是我继续debug找到了，at_items: AtItems = await self.summarize_queue.get()这行代码进入到这个方法中的时候判断self是否为空，如果为空就一直等待await getter
首次评论视频的时候跑到这里self都是空，所以就一直在等待，而外面的at_items: AtItems = await self.summarize_queue.get()也就没有获取到值，就卡在这了。
也就是说在检测到获取评论的时候
`    async def dispatch_task(self, data: AtItems):
        content = data["item"]["source_content"]
        _LOGGER.info(f"开始处理消息，内容为：{content}")
        summarize_keyword = self.value_manager.get_variable("summarize-keywords")
        evaluate_keyword = self.value_manager.get_variable("evaluate-keywords")
        for keyword in summarize_keyword:
            if keyword in content:
                _LOGGER.info(f"检测到关键字 {keyword} ，放入【总结】队列")
                await self.summarize_queue.put(data)
                return
        for keyword in evaluate_keyword:
            if keyword in content:
                _LOGGER.info(f"检测到关键字{keyword}，放入【锐评】队列")
                await self.evaluate_queue.put(data)
                return
        _LOGGER.debug(f"没有检测到关键字，跳过")`
self.summarize_queue.put就把数据放进去了，可是到后面调完gpt接口写入本地的缓存之后就变成空了。是不是在哪里get出来了？python我不太懂，也只能跟着debug来推理。
你跑的时候没有出现我这种情况嘛？我在本地跑，服务器上跑，家里的电脑，公司的电脑，同事的电脑跑都出现这个问题

**Comment by PawNzZi** [comment]
> 奇怪，我这边真的没查出来问题所在，我运行起来一切正常，这行代码是阻塞的，就是等待队列中被放入数据，按理来说没有出错的可能性

不好意思，逻辑我搞错了，之前的那行代码没有问题，代码没往下走是正常的，因为队列里的东西已经被取出来执行了。问题的确是视频首次评论不会调回复评论的接口。问题是在
`    async def _send_reply(
            self, at_items: AtItems, resp: dict, video_info: dict, _uuid: str
    ):
        _LOGGER.debug(f"正在将结果加入发送队列，等待回复")
        reply_data = copy.deepcopy(at_items)
        reply_data["item"]["ai_response"] = resp
        await self.reply_queue.put(reply_data)
        _LOGGER.debug(f"结果加入发送队列成功")
         self.task_status_recorder.update_record(
             _uuid, stage=TaskProcessStage.WAITING_PUSH_TO_CACHE
         )
        self.cache.set_cache(
            key=video_info["bvid"], value=self.cut_items_leaves(reply_data)
        )
        self.task_status_recorder.update_record(
            _uuid,
            stage=TaskProcessStage.END,
            end_reason=TaskProcessEndReason.NORMAL,
            gmt_end=int(time.time()),
        )
        _LOGGER.debug(f"设置缓存成功")
        return True`

await self.reply_queue.put(reply_data) 这行代码，github上的代码没有加await，没有发送评论就是因为这个导致的。
加了await之后就ok了。

**Comment by roitium** [comment]
呜呜呜我的问题...我一直以为是上方逻辑的问题，结果竟然是下面的异步操作忘了等待...😭这一段脑子有点短路

**Comment by PawNzZi** [comment]
我也找错地方了，逻辑没搞对。重心也都在上面那串代码。现在ojbk了，我要开始二开了。哈哈！！！！

**Comment by PawNzZi** [comment]
> 呜呜呜我的问题...我一直以为是上方逻辑的问题，结果竟然是下面的异步操作忘了等待...😭这一段脑子有点短路

话说多账号负载均衡这个需求，你的实现思路是什么？我现在在写这个功能，遇到个瓶颈，就是现在没法查询openai的余额，找不到相应的接口。
我的思路是在探测有任务进来的时候dispatch_task这个方法内去查询数据库，拿到符合条件的key，动态设置self.value_manager.set_variable("api-key", self.api_key)。然后在发送评论完成之后查询key的余额，最后更新数据库。
简单点说就是给一个默认的key，然后在每次探测到任务的时候去数据库取符合条件的key，发送完评论后查询余额，更新数据库。这样一次扔个十几二十个key到数据库里，就够玩一段时间了。不停的往数据库扔key就完事了。不知道你有没有更好的想法

**Comment by roitium** [comment]
不要拿openai账户余额，很多人使用的是第三方的api接口，不能保证都有余额接口（当然如果你自己用的话都无所谓了，你说的这个方法最好实现，现有代码基本不用动了）。我设想的是让用户主动给出一个最高限额，并给出多个key，每次运行完update一下数据库，算法上实现也不难。不过openai的请求部分需要加一个错误重试，当返回余额不足时mark一下该key，以后不再使用，然后切换到另一个key再请求

**Comment by roitium** [comment]
另外我还是想把处理流程再抽象一下，现在一个处理链包含的东西感觉还是太多了，最近想加个“基于原总结提问”的功能，发现很多处理流程都能复用hhhhhh

**Comment by roitium** [comment]
> 我也找错地方了，逻辑没搞对。重心也都在上面那串代码。现在ojbk了，我要开始二开了。哈哈！！！！

哦对了，所以你修改了哪里？我找不出来= =

**Comment by PawNzZi** [comment]
> > 我也找错地方了，逻辑没搞对。重心也都在上面那串代码。现在ojbk了，我要开始二开了。哈哈！！！！
> 
> 哦对了，所以你修改了哪里？我找不出来= =

self.reply_queue.put(reply_data)
就是这行代码前加一个 await 就可以了，_send_reply方法里面的。

**Comment by PawNzZi** [comment]
> 另外我还是想把处理流程再抽象一下，现在一个处理链包含的东西感觉还是太多了，最近想加个“基于原总结提问”的功能，发现很多处理流程都能复用hhhhhh

debug了几天，发现很多地方的确是可以复用的。刚学python，拿来练下手。

**Comment by PawNzZi** [comment]
> 不要拿openai账户余额，很多人使用的是第三方的api接口，不能保证都有余额接口（当然如果你自己用的话都无所谓了，你说的这个方法最好实现，现有代码基本不用动了）。我设想的是让用户主动给出一个最高限额，并给出多个key，每次运行完update一下数据库，算法上实现也不难。不过openai的请求部分需要加一个错误重试，当返回余额不足时mark一下该key，以后不再使用，然后切换到另一个key再请求

你这种不是算余额了，是先通过余额来算token，算出最大上限的token，用token来判断是吧？

**Comment by roitium** [comment]
是，因为单纯使用api查询余额复用性大概率不佳，有的第三方api提供商可能不会开这个接口。给出最大token实际上也是变相的“余额”

**Comment by roitium** [comment]
我现在能想出来的最佳实践是整个管理器，统一调度key的分配，暴露出来相关接口

**Comment by PawNzZi** [comment]
> 是，因为单纯使用api查询余额复用性大概率不佳，有的第三方api提供商可能不会开这个接口。给出最大token实际上也是变相的“余额”

这种也行，已经实现了，在生成promt的时候计算token，然后去数据库查满足token的key，在response中有总共使用的token，再去数据库减掉使用的token就可以了。

**Comment by roitium** [comment]
大佬牛蛙！如果可以的话提个pr就更好了嘿嘿嘿

**Comment by PawNzZi** [comment]
> 大佬牛蛙！如果可以的话提个pr就更好了嘿嘿嘿

我不是啥大佬啊，这个是我第一次写python代码。也没那么复杂啊，在生成promt的时候用tiktoken计算token，再加1000，连接数据库查找符合条件的key，openai响应之后你是记录了total_token的，再update一下数据库，减去total_token就可以了。数据库里有个字段记录最大上限的token。pr太丢脸了，我怕刚学写的代码太垃圾。而且我改了很多地方，不一定符合你的想法。对了，回复的评论被b站吞掉的原因我也找到了，你在回复的地方拼接了项目的地址，我删了之后就没被吞过。
