### ISSUE TITLE
项目启动起来了，

### ISSUE THREAD

**Issue by PawNzZi** [yanyao2333/BiliGPTHelper#10]
目前遇到几个问题：
 第一个报错：
`Job "Session.run.<locals>.qurey (trigger: interval[0:00:06], next run at: 2024-02-17 14:49:17 CST)" raised an exception
Traceback (most recent call last):
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\bilibili_api\session.py", line 502, in qurey
    js: dict = await new_sessions(self.credential, self.maxTs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\bilibili_api\session.py", line 79, in new_sessions
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\aiohttp\client.py", line 605, in _request
    await resp.start(conn)
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "E:\biliGPT\v3\BiliGPTHelper\venv\Lib\site-packages\aiohttp\streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。`
项目启动之后会一直循环报这个错，疑似新版bilibiliapi的问题？

第二个报错：bili_linsten.py文件中
` for item in reversed(data["items"]):
            if item["at_time"] > self.last_at_time:
                _LOGGER.debug(f"at_time{item['at_time']}大于last_at_time{self.last_at_time}，放入新消息队列")
                item["user"] = data["items"]["user"] 
                new_items.append(item) `
item["user"] = data["items"]["user"]  这行代码应该注释掉吧？不然逻辑不通，不注释也会报错。

第三个报错：bili_linsten.py文件中
原代码：
`async def build_task_from_at_msg(self, msg: dict) -> BiliGPTTask | None:
        try:
            event = deepcopy(msg)
            if msg["type"] != "reply" or msg["business_id"] != 1:
                _LOGGER.warning("不是回复消息，跳过")
                return None
            elif msg["item"]["root_id"] == 0 and msg["item"]["target_id"] == 0:
                _LOGGER.warning("该消息是楼中楼消息，暂时不受支持，跳过处理")
                return None
            event["source_type"] = "bili_comment"
            event["raw_task_data"] = deepcopy(msg)
            event["source_extra_attr"] = BiliAtSpecialAttributes.model_validate(event)
            event["sender_id"] = event["user"]["mid"]
            event["video_url"] = event["uri"]
            event["source_command"] = event["source_content"]
            event["video_id"] = await BiliVideo(url=event["uri"]).bvid
            task_metadata = BiliGPTTask.model_validate(event)
        except Exception:
            traceback.print_exc()
            _LOGGER.error("在验证任务数据结构时出现错误，跳过处理！")
            return None

        return task_metadata`

本地修改后：
` async def build_task_from_at_msg(self, msg: dict) -> BiliGPTTask | None:
        try:
            event = deepcopy(msg)
            if msg["item"]["type"] != "reply" or msg["item"]["business_id"] != 1:
                _LOGGER.warning("不是回复消息，跳过")
                return None
            elif msg["item"]["root_id"] != 0 or msg["item"]["target_id"] != 0:
                _LOGGER.warning("该消息是楼中楼消息，暂时不受支持，跳过处理")
                return None
            event["source_type"] = "bili_comment"
            event["raw_task_data"] = deepcopy(msg)
            event["source_extra_attr"] = BiliAtSpecialAttributes.model_validate(event["item"])
            event["sender_id"] = str(event["user"]["mid"])
            event["video_url"] = event["item"]["uri"]
            event["source_command"] = event["item"]["source_content"]
            event["video_id"] = await BiliVideo(credential=self.credential, url=event["item"]["uri"]).bvid
            task_metadata = BiliGPTTask.model_validate(event)
        except Exception as e:
            traceback.print_exc()
            _LOGGER.error(e)
            _LOGGER.error("在验证任务数据结构时出现错误，跳过处理！")
            return None

        return task_metadata`
这个是我本地修改之后的代码，第二个问题的循环结束后会调用这个方法，参数是new_items循环的item
结合上面的逻辑所以好几处的值都是在event['item']中，楼中楼的判断值不等0才是。
但是修改完后执行到event["video_id"] = await BiliVideo(credential=self.credential, url=event["item"]["uri"]).bvid的时候直接捕获异常了，提示请求超时。
以上是遇到的几个问题，能启动，但是跑不通。都是在调用bilibliapi时报错，不知道是新版本的api问题还是账号问题，晚些换个账号再测试下。不清楚你的逻辑，上述问题是否存在我所说的bug，如是，我晚些提个PR

**Comment by roitium** [comment]
1. 第一个问题我也有，我一直怀疑是我网络的问题，那现在看来是新版 api 的问题，不过不影响使用，就是日志有点烦，到时候我 catch 一下
2. 我 at 触发消息没条件测试，两个账号不知道为啥互相 at 从来没成功过...你这点改好了直接给我 pr 吧

**Comment by PawNzZi** [comment]
> 1. 第一个问题我也有，我一直怀疑是我网络的问题，那现在看来是新版 api 的问题，不过不影响使用，就是日志有点烦，到时候我 catch 一下
> 2. 我 at 触发消息没条件测试，两个账号不知道为啥互相 at 从来没成功过...你这点改好了直接给我 pr 吧

代码提交了，有时间你合并下。我还是对这个项目比较感兴趣的，是否留个WX，有问题可以迅速沟通，也可以跟dalao学下python。可以的话wx发我邮箱吧：roy20fwmeng@gmail.com

**Comment by roitium** [comment]
发了，不是什么大佬，只不过又菜又爱玩🤣

**Comment by PawNzZi** [comment]
> 发了，不是什么大佬，只不过又菜又爱玩🤣

加你了。可能不能喝

**Comment by roitium** [comment]
commit bf52870d2 给ClientOSError加了个warning提示，告诉别人不影响运行
这个issue我就先关了
