### ISSUE TITLE
docker部署latest镜像报错

### ISSUE THREAD

**Issue by cj1357** [yanyao2333/BiliGPTHelper#2]
提示：ModuleNotFoundError: No module named 'whisper'

**Comment by cj1357** [comment]
配置文件whisper默认应该都是关了的
![image](https://github.com/yanyao2333/BiliGPTHelper/assets/40661342/05926bef-14f3-4f4d-9771-1634daa69df9)

**Comment by roitium** [comment]
果咩呐塞！修复了导入whisper的顺序，重新拉镜像就好了

**Comment by cj1357** [comment]
太好了！感谢😸
