### ISSUE TITLE
新版本还在开发嘛？

### ISSUE THREAD

**Issue by PawNzZi** [yanyao2333/BiliGPTHelper#6]
最近闲下来了，看下下代码，好多都重构了，是还在重构中嘛？
把代码clone下来，好几个地方都在报错。好几处bug。

**Comment by roitium** [comment]
qaq，前一段时间确实比较忙，重构了一部分，还没完成。最近一段放寒假了，会继续维护的

**Comment by PawNzZi** [comment]
我就说嘛，改了好多还是跑不通。有时间我提个pr吧。> qaq，前一段时间确实比较忙，重构了一部分，还没完成。最近一段放寒假了，会继续维护的

**Comment by roitium** [comment]
恐怕你改起来会比较困难（因为当时重构到了api数据结构部分，要把b站的返回内容封装成数据模型，这块有、繁琐

**Comment by PawNzZi** [comment]
> 恐怕你改起来会比较困难（因为当时重构到了api数据结构部分，要把b站的返回内容封装成数据模型，这块有、繁琐

那还是等你搞完我再来查缺补漏吧。对了，还有一个问题，就是cookie刷新的问题，账号过期后重新刷新cookie总是失败。过几天就得手动替换下cookie。这个你遇到过嘛？

**Comment by roitium** [comment]
> > 恐怕你改起来会比较困难（因为当时重构到了api数据结构部分，要把b站的返回内容封装成数据模型，这块有、繁琐
> 
> 那还是等你搞完我再来查缺补漏吧。对了，还有一个问题，就是cookie刷新的问题，账号过期后重新刷新cookie总是失败。过几天就得手动替换下cookie。这个你遇到过嘛？

这个 cookie 自动刷新我反正是没成功过，但是 bilibili-api 库提供这个方法，我就合进去了

**Comment by PawNzZi** [comment]
haha，好吧。我再研究下自动刷新。主要是很神奇，我之前是部署在usa的服务器上，刷新失败很多次，就懒得管了，昨天晚上突然发现刷新成功了。有好几个月没管了。
